import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "John",
      last_name: "Doe",
      email: "doko@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
      phone: "123456789",
      age: 20,
    },
    {
      name: "Jehn",
      last_name: "Doe",
      email: "vero@gmailcom",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
      phone: "123456789",
      age: 28,
    },
  ],
  products: [
    {
      title: "Producto1",
      brand: "Scott",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
      especification: {
        peso: 10,
        genero: "Hombre",
        garantia: true,
        modelo: "Corvus",
        material: "Acero",
      },
      idUser: 0,
      precio: 10,
      vendido: 10,
      cantidad: 10,
      discount: 50,
      img: "https://media.4rgos.it/s/Argos/9520103_R_SET?$Main768$&w=620&h=620",
    },
    {
      title: "Bicicleta Best Corvus Aro 27.5 Negro",

      brand: "Specialized",
      description:
        "La mejor bicicleta del mundo de los ultimos tiempo con una gran variabilidad de movimiento y mejora en todo sus campos del ciclismo ",
      especification: {
        peso: 10,
        genero: "Hombre",
        garantia: true,
        modelo: "Corvus",
        material: "Acero",
      },
      idUser: 1,
      precio: 20,
      vendido: 20,
      cantidad: 20,
      discount: 20,

      img: "https://www.tradeinn.com/h/13828/138280931/specialized-bicicleta-mtb-rockhopper-29.jpg",
    },
    {
      title: "Producto3",
      brand: "Orbea bikes",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
      especification: {
        peso: 10,
        genero: "Hombre",
        garantia: true,
        modelo: "Corvus",
        material: "Acero",
      },
      idUser: 2,
      precio: 30,
      vendido: 30,
      cantidad: 30,
      discount: 40,
      img: "https://media.4rgos.it/s/Argos/9520103_R_SET?$Main768$&w=620&h=620",
    },
    {
      title: "Producto4",
      brand: "Scott",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
      especification: {
        peso: 10,
        genero: "Hombre",
        garantia: true,
        modelo: "Corvus",
        material: "Acero",
      },
      idUser: 3,
      precio: 40,
      vendido: 40,
      cantidad: 0,
      discount: 50,
      img: "https://media.4rgos.it/s/Argos/9520103_R_SET?$Main768$&w=620&h=620",
    },
    {
      title: "Producto5",
      brand: "cannondale",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
      especification: {
        peso: 10,
        genero: "Hombre",
        garantia: true,
        modelo: "Corvus",
        material: "Acero",
      },
      idUser: 4,
      precio: 50,
      vendido: 50,
      cantidad: 50,
      discount: 10,
      img: "https://media.4rgos.it/s/Argos/9520103_R_SET?$Main768$&w=620&h=620",
    },
  ],
};

export default data;
